export const FALLBACK_HOSPITALS = [
  // North & North-West Riyadh / Diriyah
  {
    id: 'diriyah-hosp',
    name: 'Diriyah Hospital',
    nameAr: 'مستشفى الدرعية',
    city: 'Riyadh',
    specialties: ['General Surgery', 'Pediatrics', 'Orthopedics', 'Ophthalmology'],
    address: 'Diriyah, Riyadh 13711',
    lat: 24.7562,
    lng: 46.5394,
  },
  {
    id: 'dallah-nakheel',
    name: 'Dallah Hospital Al Nakheel',
    nameAr: 'مستشفى دله - النخيل',
    city: 'Riyadh',
    specialties: ['Cardiology', 'Orthopedics', 'Ophthalmology', 'Pediatrics'],
    address: 'Al Nakheel, Riyadh 12382',
    lat: 24.7469,
    lng: 46.6358,
  },
  {
    id: 'habib-sahafa',
    name: 'Dr. Sulaiman Al Habib Hospital Al Sahafa',
    nameAr: 'مستشفى د. سليمان الحبيب - الصحافة',
    city: 'Riyadh',
    specialties: ['Cardiology', 'Dermatology', 'Orthopedics', 'Neurology', 'Ophthalmology'],
    address: 'Al Sahafa, Riyadh 13321',
    lat: 24.7963,
    lng: 46.6327,
  },
  {
    id: 'kingdom-hosp',
    name: 'Kingdom Hospital',
    nameAr: 'مستشفى المملكة',
    city: 'Riyadh',
    specialties: ['Pediatrics', 'Ophthalmology', 'General Surgery', 'Cardiology'],
    address: 'Al Rabie, Riyadh 13316',
    lat: 24.8058,
    lng: 46.6578,
  },
  {
    id: 'saudi-german',
    name: 'Saudi German Hospital',
    nameAr: 'المستشفى السعودي الألماني',
    city: 'Riyadh',
    specialties: ['Orthopedics', 'Oncology', 'Neurology', 'Cardiology'],
    address: 'Al Sahafa, Riyadh 13321',
    lat: 24.7891,
    lng: 46.6186,
  },
  // Central & West Riyadh
  {
    id: 'habib-takhassusi',
    name: 'Dr. Sulaiman Al Habib Al Takhassusi',
    nameAr: 'مستشفى د. سليمان الحبيب - التخصصي',
    city: 'Riyadh',
    specialties: ['Cardiology', 'Orthopedics', 'Dermatology', 'Ophthalmology'],
    address: 'Al Rahmaniyah, Riyadh 12344',
    lat: 24.7069,
    lng: 46.6631,
  },
  {
    id: 'kfsh-riyadh',
    name: 'King Faisal Specialist Hospital',
    nameAr: 'مستشفى الملك فيصل التخصصي',
    city: 'Riyadh',
    specialties: ['Oncology', 'Cardiology', 'Neurology', 'Orthopedics'],
    address: 'Al Mathar Ash Shamali, Riyadh 11564',
    lat: 24.6705,
    lng: 46.6787,
  },
  {
    id: 'kfmc-riyadh',
    name: 'King Fahad Medical City',
    nameAr: 'مدينة الملك فهد الطبية',
    city: 'Riyadh',
    specialties: ['Neurology', 'Orthopedics', 'Pediatrics', 'Oncology'],
    address: 'As Sulimaniyah, Riyadh 12231',
    lat: 24.6894,
    lng: 46.7042,
  },
  // East & South Riyadh
  {
    id: 'habib-rayyan',
    name: 'Dr. Sulaiman Al Habib Al Rayyan',
    nameAr: 'مستشفى د. سليمان الحبيب - الريان',
    city: 'Riyadh',
    specialties: ['Cardiology', 'Orthopedics', 'Pediatrics', 'General Surgery'],
    address: 'Al Rayyan, Riyadh 14212',
    lat: 24.7145,
    lng: 46.7728,
  },
  {
    id: 'mouwasat-riyadh',
    name: 'Mouwasat Hospital',
    nameAr: 'مستشفى المواساة',
    city: 'Riyadh',
    specialties: ['Orthopedics', 'Ophthalmology', 'Neurology', 'Cardiology'],
    address: 'Al Gharnatah, Riyadh 13241',
    lat: 24.7831,
    lng: 46.7380,
  },
  {
    id: 'habib-suwaidi',
    name: 'Dr. Sulaiman Al Habib Al Suwaidi',
    nameAr: 'مستشفى د. سليمان الحبيب - السويدي',
    city: 'Riyadh',
    specialties: ['Pediatrics', 'Orthopedics', 'General Surgery', 'Cardiology'],
    address: 'Al Suwaidi, Riyadh 12791',
    lat: 24.5824,
    lng: 46.6714,
  },
  {
    id: 'dallah-namar',
    name: 'Dallah Hospital Namar',
    nameAr: 'مستشفى دله - نمار',
    city: 'Riyadh',
    specialties: ['General Surgery', 'Orthopedics', 'Pediatrics', 'Dermatology'],
    address: 'Namar, Riyadh 14923',
    lat: 24.5683,
    lng: 46.6872,
  },
  // Jeddah & Dammam
  {
    id: 'kauh-jeddah',
    name: 'King Abdulaziz University Hospital',
    nameAr: 'مستشفى جامعة الملك عبدالعزيز',
    city: 'Jeddah',
    specialties: ['Cardiology', 'Dermatology', 'General Surgery', 'Ophthalmology'],
    address: 'Al Jamiah, Jeddah 21589',
    lat: 21.4988,
    lng: 39.2274,
  },
  {
    id: 'kfgh-jeddah',
    name: 'King Fahad General Hospital',
    nameAr: 'مستشفى الملك فهد العام',
    city: 'Jeddah',
    specialties: ['Orthopedics', 'Neurology', 'General Surgery'],
    address: 'Al Andalus, Jeddah 23325',
    lat: 21.5262,
    lng: 39.1706,
  },
  {
    id: 'kfsh-dammam',
    name: 'King Fahad Specialist Hospital',
    nameAr: 'مستشفى الملك فهد التخصصي',
    city: 'Dammam',
    specialties: ['Cardiology', 'Oncology', 'Orthopedics', 'Pediatrics'],
    address: 'Al Muraikabat, Dammam 32253',
    lat: 26.3541,
    lng: 50.1872,
  },
];

export const FALLBACK_DOCTORS = [
  // Diriyah
  {
    id: 'doc-diriyah-1',
    name: 'Dr. Saud Al-Diriyyah',
    nameAr: 'د. سعود الدرعية',
    specialty: 'Ophthalmology',
    city: 'Riyadh',
    languages: ['Arabic', 'English'],
    hospitalId: 'diriyah-hosp',
    hospital: FALLBACK_HOSPITALS[0],
  },
  {
    id: 'doc-diriyah-2',
    name: 'Dr. Bandar Al-Otaibi',
    nameAr: 'د. بندر العتيبي',
    specialty: 'Orthopedics',
    city: 'Riyadh',
    languages: ['Arabic', 'English'],
    hospitalId: 'diriyah-hosp',
    hospital: FALLBACK_HOSPITALS[0],
  },

  // Dallah Nakheel
  {
    id: 'doc-nakheel-1',
    name: 'Dr. Tariq Al-Mansoor',
    nameAr: 'د. طارق المنصور',
    specialty: 'Ophthalmology',
    city: 'Riyadh',
    languages: ['Arabic', 'English'],
    hospitalId: 'dallah-nakheel',
    hospital: FALLBACK_HOSPITALS[1],
  },
  {
    id: 'doc-nakheel-2',
    name: 'Dr. Khaled Al-Ghamdi',
    nameAr: 'د. خالد الغامدي',
    specialty: 'Orthopedics',
    city: 'Riyadh',
    languages: ['Arabic', 'English'],
    hospitalId: 'dallah-nakheel',
    hospital: FALLBACK_HOSPITALS[1],
  },

  // Habib Sahafa
  {
    id: 'doc-sahafa-1',
    name: 'Dr. Nora Al-Subaie',
    nameAr: 'د. نورة السبيعي',
    specialty: 'Ophthalmology',
    city: 'Riyadh',
    languages: ['Arabic', 'English'],
    hospitalId: 'habib-sahafa',
    hospital: FALLBACK_HOSPITALS[2],
  },

  // Kingdom Hospital
  {
    id: 'doc-kingdom-1',
    name: 'Dr. Reem Al-Kahlil',
    nameAr: 'د. ريم الخليل',
    specialty: 'Ophthalmology',
    city: 'Riyadh',
    languages: ['Arabic', 'English'],
    hospitalId: 'kingdom-hosp',
    hospital: FALLBACK_HOSPITALS[3],
  },

  // Habib Takhassusi
  {
    id: 'doc-takhassusi-1',
    name: 'Dr. Faisal Al-Shammari',
    nameAr: 'د. فيصل الشمري',
    specialty: 'Ophthalmology',
    city: 'Riyadh',
    languages: ['Arabic', 'English'],
    hospitalId: 'habib-takhassusi',
    hospital: FALLBACK_HOSPITALS[5],
  },

  // KFMC
  {
    id: 'doc-kfmc-1',
    name: 'Dr. Mohammed Al-Qahtani',
    nameAr: 'د. محمد القحطاني',
    specialty: 'Orthopedics',
    city: 'Riyadh',
    languages: ['Arabic', 'English'],
    hospitalId: 'kfmc-riyadh',
    hospital: FALLBACK_HOSPITALS[7],
  },

  // Mouwasat
  {
    id: 'doc-mouwasat-1',
    name: 'Dr. Wafa Al-Harbi',
    nameAr: 'د. وفاء الحربي',
    specialty: 'Ophthalmology',
    city: 'Riyadh',
    languages: ['Arabic', 'English'],
    hospitalId: 'mouwasat-riyadh',
    hospital: FALLBACK_HOSPITALS[9],
  },

  // Jeddah
  {
    id: 'doc-jeddah-1',
    name: 'Dr. Amal Al-Shehri',
    nameAr: 'د. أمل الشهري',
    specialty: 'Ophthalmology',
    city: 'Jeddah',
    languages: ['Arabic', 'English'],
    hospitalId: 'kauh-jeddah',
    hospital: FALLBACK_HOSPITALS[12],
  },

  // Dammam
  {
    id: 'doc-dammam-1',
    name: 'Dr. Ali Al-Ghamdi',
    nameAr: 'د. علي الغامدي',
    specialty: 'Orthopedics',
    city: 'Dammam',
    languages: ['Arabic', 'English'],
    hospitalId: 'kfsh-dammam',
    hospital: FALLBACK_HOSPITALS[14],
  },
];
